db:
  main:
    addr: ${MAIN_DB_ADDR}
    port: ${MAIN_DB_PORT}
    name: ${MAIN_DB_NAME}
    user: ${MAIN_DB_USER}
    password: ${MAIN_DB_PASSWD}
    charset: utf8mb4

grpc:
  address: ${GRPC_SERVER_ADDRESS}

log:
  fileName: ${LOG_FILE_NAME}